### PR TITLE
Add plugin hook for workflow

### PR DESCRIPTION
**Pull request by oyvindeide**

### CODE REVIEW

**Comment by markusdregi** [comment]
Are we planning to also support passing documentation similarly to what we have done for the forward models? :) I'm asking on behalf of https://github.com/equinor/ert/issues/982

**Comment by oyvindeide** [comment]
Most definitely, yes. I am working on setting up the hooks on the `ert` side. Though my approach will be slightly different than for forward models. It will be more explicit, that you have to add the documentation to a hook, something like this:
```
@hook_implementation
def ert_workflow(config):
    workflow = config.add_workflow(
        CorrelatedObservationsScalingJob, "CORRELATED_OBSERVATIONS_SCALING"
    )
    workflow.description = "Correlated observation scaling will scale observations."
```
But if you have other ideas I am happy to discuss them.

**Comment by oyvindeide** [comment]
Implementation is here: https://github.com/equinor/ert/pull/974

**Comment by markusdregi** [comment]
No other ideas ;) Just wanted to link the issues if they indeed are related. Because now I think we should wait for this to ensure `CSV_EXPORT2` documentation.

**Comment by oyvindeide** [comment]
This has been split into:

https://github.com/equinor/semeio/pull/158
https://github.com/equinor/semeio/pull/157
https://github.com/equinor/semeio/pull/156
https://github.com/equinor/semeio/pull/159

Closing this

**Pull request closed without merging**
