### PR TITLE
Blacken with black 20.8b0

### PR DESCRIPTION
**Pull request by berland**
Going from black 19.10b0 to 20.8b0, black will modify the source code.

Could potentially pin the black version in CI setup.

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by oyvindeide** [comment]
Jenkins: test this please

**Comment by oyvindeide** [comment]
This looks great, thanks for doing it, do you know why it fails though? Black says one file would be reformatted.

**Comment by berland** [comment]
Failed CI was due to missing local rebase.

Another thing, when `pre-commit` is installing black on CI, I think we are getting the `stable` branch straight from github. Should semeio be more in control of which black version to run?

**Comment by oyvindeide** [comment]
> Failed CI was due to missing local rebase.
> 
> Another thing, when `pre-commit` is installing black on CI, I think we are getting the `stable` branch straight from github. Should semeio be more in control of which black version to run?

I am not sure what I think, it is quite annoying when this happens, but at the same time, we get a reminder to update it. I considered asking you to pin it in this PR, but decided against it.

**Review by oyvindeide — APPROVED** [review]
LGTM! Thanks for updating!

**Pull request merged**
