### PR TITLE
Fix minor documentation issues ahmanalysis

### PR DESCRIPTION
**Pull request by lars-petter-hauge**

### CODE REVIEW

**Review by eivindjahren — APPROVED** [review]

**Review by oyvindeide — CHANGES_REQUESTED** [review]
I object to the commit message, otherwise fine.

**Comment by lars-petter-hauge** [comment]
> I object to the commit message, otherwise fine.

Better?

**Review by oyvindeide — APPROVED** [review]
Better, but capital Examples? ;)

**Comment by lars-petter-hauge** [comment]
I expect the same level of precision in the review for any PR coming in ;)

**Pull request merged**
