### PR TITLE
Remove UMASK and LOG_LEVEL from test ert configs

### PR DESCRIPTION
**Pull request by berland**
These keywords are removed from ERT.

### CODE REVIEW

**Review by xjules — APPROVED** [review]
LGMT

**Comment by hnformentin** [comment]
Could you take a look in the tests? It seems already approved, just needing to have tests green..,

**Comment by xjules** [comment]
This one need to be updated @berland

**Comment by berland** [comment]
> This one needs to be updated @berland

Waiting for a new stable tag of ert to have tests passing.

**Pull request merged**
