### PR TITLE
CSV export to non-existing directory

### PR DESCRIPTION
**Pull request by berland**
Solves #149

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by oysteoh** [comment]
There should be a squash of the commits at least - other than that It looks fine ! But - we had a small discussion on slack which didn't conclude I think - @markusdregi - should we make directories or not?

**Comment by oyvindeide** [comment]
The consensus was we should not make directories. The main argument was that making directories could mask different issues. A better solution would be to catch the error and provide good feedback. If there are strong counter arguments though, we are all ears.

A second point is I am against relying on `ert-statoil` test data, at least as the only means of testing something, and new tests should be created using open data.

**Comment by markusdregi** [comment]
The conclusion yesterday was as @oyvindeide mentions. But the discussion can be reopened if you are opinionated ;) However, what I would like to do is for us to agree and then I'll write up some `FMU`-dev conventions. I think the users would benefit greatly from consistent behaviour in these cases...

A thought I had yesterday evening was whether we should make a workflow that creates the necessary folder structure at the beginning of the run?

```
CREATE_FOLDER_STRUCTURE ../input/folder_structure.yml --root=..
```

```yaml
# ../input/folder_structure

input:
  some_data:
  the_secret_sauce:
    ingredient1:
    ingredient2:
config:
output:
  exports:
  storage:
```

Could this be a solution?

**Comment by oyvindeide** [comment]
I've seen that discussion before somewhere? Yammer perhaps? Were you a part of that, and remember the outcome? I've no strong opinion on the matter.

**Comment by berland** [comment]
I added some details on the Reek configuration in the issue, #149. Since it is in Reek and used in the course, we should expect this to be widespread, and it does not work currently with CSV_EXPORT2.

Is there a clean way today to create a folder for a workflow? I am not aware.

**Comment by markusdregi** [comment]
I think we have two options:
- implement the above job and install it both as a workflow and a forward model job to create a batch of folders. Could be useful and reduce the need for 20 steps in the forward model to create nothing but folders 🤷 
- reevaluate our decision and decide that workflows and jobs in general should all create the necessary folders to write their output.

Personally I'm leaning towards the first...

**Comment by berland** [comment]
What should be our recommendation for workaround today? MAKE_FOLDER run as a FORWARD_MODEL?

**Comment by markusdregi** [comment]
I can implement an MVP of the above `CREATE_FOLDER_STRUCTURE` if we believe it is a good idea. I think @eivindsm patched the HM tutorial by changing the path to something that already existed...

**Comment by berland** [comment]
> A second point is I would like to avoid relying on `ert-statoil` test data, at least as the only means of testing something, and new tests should be created using open data.

Shifted this problem to #152

**Pull request closed without merging**
