### PR TITLE
Fix switch from xlrd to openpyxl as engine in pandas

### LINKED ISSUE #273: MIgrate to openpyxl (or at least get rid of xldr<2 requirement)
xldr was pinned to <2 since version 2 refuse to parse other spreadsheet files besides xls files

### PR DESCRIPTION
**Pull request by oyvindeide**
Closes #273

### CODE REVIEW

**Comment by hnformentin** [comment]
Hello! A curiosity: would not be useful to report users that columns with NAs would be dropped? Or xldr had this same behaviour?

**Comment by oyvindeide** [comment]
With this we drop support of `xls`-files. I think that is fine, and discussing with @berland the input to this job is mostly generated by https://github.com/equinor/fmu-tools/blob/db5faad96cd4500b31801fbcc34c4f41d8ee018f/src/fmu/tools/sensitivities/fmudesignrunner.py#L103, which will create `xlsx` files. I can add a check for extension, but `xls` was last used in Excel 2003 so seems redundant.

**Comment by oyvindeide** [comment]
> Hello! A curiosity: would not be useful to report users that columns with NAs would be dropped? Or xldr had this same behaviour?

This was the old behavior, which is why I added it. Columns with only spaces in them would not be read, they are in `openpyxl`. We have a test ensuring that columns with only spaces are dropped, so it is desired behavior.

**Comment by hnformentin** [comment]
Thanks. That's good, the `how=all` specifies only columns where all are NA! Great!

**Review by hnformentin — APPROVED** [review]
LGTM!

**Pull request merged**
