### PR TITLE
Use facade to get grid in localisation workflow config

### PR DESCRIPTION
**Pull request by oysteoh**

### CODE REVIEW

**Comment by oysteoh** [comment]
Jenkins: Test this please!

**Comment by valentin-krasontovitsch** [comment]
found the following in the logs:

```
E           Exception ignored in: <function BaseCClass.__del__ at 0x7fd8ce6ca040>
E           Traceback (most recent call last):
E             File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/cwrap/basecclass.py", line 140, in __del__
E               self.free()
E             File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/cwrap/basecclass.py", line 124, in free
E               raise NotImplementedError("A BaseCClass requires a free method implementation!")
E           NotImplementedError: A BaseCClass requires a free method implementation!
E           Exception ignored in: <function BaseCClass.__del__ at 0x7fd8ce6ca040>
E           Traceback (most recent call last):
E             File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/cwrap/basecclass.py", line 140, in __del__
E               self.free()
E             File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/cwrap/basecclass.py", line 124, in free
E               raise NotImplementedError("A BaseCClass requires a free method implementation!")
E           NotImplementedError: A BaseCClass requires a free method implementation!
E           Exception ignored in: <function BaseCClass.__del__ at 0x7fd8ce6ca040>
E           Traceback (most recent call last):
E             File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/cwrap/basecclass.py", line 140, in __del__
E               self.free()
E             File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/cwrap/basecclass.py", line 124, in free
E               raise NotImplementedError("A BaseCClass requires a free method implementation!")
E           NotImplementedError: A BaseCClass requires a free method implementation!
E           Simulations failed with the following error: Analysis of simulation failed with the following error: No active observations for update step: ALL_ACTIVE.
E           
E           Analysis of simulation failed with the following error: No active observations for update step: ALL_ACTIVE.

/tmp/jenkins-scout-f_scout_ci/workspace/komodo_testin-pr/test-root/tests/jobs/rft/test_gendata_rft.py:688: AssertionError
```

but coulnd't see in the logs which semeio class is causing this error. gonna look a bit at the (test) code.

**Comment by valentin-krasontovitsch** [comment]
i see that the test calls ert using `subprocess.run` - based on not finding any classes in semeio, this must be an ert issue :thinking:

**Comment by valentin-krasontovitsch** [comment]
apparently @eivindjahren implemented a fix in ert that should make this error message not show up anymore - maybe this is a different manifestation of the same problem, or perhaps the jenkins tests are not running an ert version that has said fix

**Pull request closed without merging**
