### PR TITLE
[csv_export2] Fix crash on missing parameters.txt

### PR DESCRIPTION
**Pull request by berland**
Solves #187 

Builds on PR #220

### CODE REVIEW

**Comment by berland** [comment]
To be rebased.

**Review by oysteoh — APPROVED** [review]
Please squash your commits and then rebase and merge 👍

**Comment by berland** [comment]
Rebased and ready to 🚢

**Comment by oyvindeide** [comment]
I have missed that this was ready - we changed the CI runner under your feet in the meantime, can you do another rebase? Same requirement as before, so should only be the rebase that is required.

**Pull request merged**
