### PR TITLE
Do garbage collection after tests to avoid storage pollution in root

### LINKED ISSUE #72: Tests leaks storage folder in root
After running the tests in a clean semeio tree I get a `storage` folder in the root folder. I suspect one of the tests using snake oil to be the sinner as `storage` contains a single folder named `snake_oil`.

### PR DESCRIPTION
**Pull request by oyvindeide**
Closes #72

### CODE REVIEW

**Comment by markusdregi** [comment]
So basically this PR moves cwd into a separate folder for the run of the test right? Any reason that folder needs to be shared?

**Comment by oyvindeide** [comment]
> So basically this PR moves cwd into a separate folder for the run of the test right? Any reason that folder needs to be shared?

It has scope `session`, so it happens once before running the tests, and does not return before the tests have completed, which is the reason for the shared folder. All the tests creating `storage` are already running in their own `tmpdir`, the problem here lies in the tear down of the tests. 

As far as I could see, there were two cases occurring, if running all the tests just adding `gc.collect` was enough from preventing getting `storage` in the wrong place. If running a subset then it was necessary to move `cwd` before the tests and restore after they were completed.

**Comment by markusdregi** [comment]
> It has scope session

I missed that part 🤷

**Review by markusdregi — APPROVED** [review]
It looks good and it also appears to succeed at its promise on my machine 👏

**Pull request merged**
