### PR TITLE
Add actionlint to lint the workflow files

### PR DESCRIPTION
**Pull request by berland**
Testing https://github.com/rhysd/actionlint

### CODE REVIEW

**Comment by berland** [comment]
This looks like a nice to have. Gave a clear error message if a workflow file was deliberately perturbed.

**Comment by hnformentin** [comment]
Could you take a look in tests (Jenkins and lint failed)?

**Comment by berland** [comment]
Needs #480  to pass linting test.

**Comment by berland** [comment]
The list of required checks in github branch protection needs an update to accomodate for the change in workflow name in this PR.

**Pull request merged**
