### PR TITLE
Fix erroneous job config for GENDATA_RFT (defaults not working)

### PR DESCRIPTION
**Pull request by berland**
Workaround is to specify the csv filename in the ert config.

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by berland** [comment]
CI fails due to `black` bumped to 20.8b0

**Comment by berland** [comment]
Rebased on top of black208b0-branch.

**Review by oyvindeide — APPROVED** [review]
LGTM! I merged your black commit, so just rebase and it is good to go.

**Pull request merged**
