### PR TITLE
Add python-package.yml file for CI with GitHub Actions

### PR DESCRIPTION
**Pull request by kvashchuka**
Closes issue #208

### CODE REVIEW

**Comment by sondreso** [comment]
This needs to be pushed to the Equinor fork to trigger to action until it is merged :slightly_smiling_face:

**Comment by oyvindeide** [comment]
Also note that `tox` is the test runner in `semeio`, and that `pre-commit` is used to run the formatting tests (which include `black`, `flake8` and `pylint`)

**Comment by oyvindeide** [comment]
See: https://github.com/equinor/semeio/blob/master/README.md

**Comment by kvashchuka** [comment]
PR #230 is created instead

**Pull request closed without merging**
